const process = ({enPage, enTitle}) => ({
  enPage,
  enTitle,
  permalink: [
    Array.isArray(enPage) ? enPage.join('-') : enPage,
    enTitle
      .replace(/\W/g, '-')
      .replace(/-+/g, '-')
      .replace(/(^-|-$)/g, '')
      .toLowerCase()
  ].join('-')
})

const pagedSources = [
  {enPage: 'ix', enTitle: `Gapminder`},
  {enPage: 1, enTitle: `X-ray`},
  {enPage: 2, enTitle: `Hans's sword swallowing`},
  {
    enPage: 3,
    enTitle: `Fact question 1: Girls in school in low-income countries`
  },
  {enPage: 3, enTitle: `Fact Question 2: Where the Majority Lives`},
  {enPage: 3, enTitle: `Fact Question 3: Extreme Poverty`},
  {enPage: 3, enTitle: `Fact Question 4: Life Expectancy`},
  {enPage: 4, enTitle: `Fact Question 5: Future Number of Children`},
  {enPage: 4, enTitle: `Fact Question 6: Why is the Population Increasing?`},
  {enPage: 4, enTitle: `Fact Question 7: Natural Disasters`},
  {enPage: 4, enTitle: `Fact Question 8: Where People Live`},
  {enPage: 4, enTitle: `Fact question 9: Vaccination`},
  {enPage: 5, enTitle: `Fact Question 10: Women's Education`},
  {enPage: 5, enTitle: `Fact Question 11: Endangered Species`},
  {enPage: 5, enTitle: `Fact Question 12: Electricity`},
  {enPage: 5, enTitle: `Fact Question 13: Climate Change`},
  {enPage: 7, enTitle: `Fact questions online`},
  {enPage: [7, 8, 'Appendix'], enTitle: `Poll results`},
  {enPage: [7, 8], enTitle: `Vaccination`},
  {enPage: 8, enTitle: `Public awareness of climate change`},
  {enPage: 10, enTitle: `Hans testing students`},
  {enPage: 12, enTitle: `World Economic Forum lecture`},
  {enPage: 13, enTitle: `The Ten Instincts in Cognitive Science`},
  {enPage: 14, enTitle: `Cognitive biases`},
  {enPage: 19, enTitle: `Child mortality in 1995 and 2017`},
  {enPage: 21, enTitle: `Improvements in Sweden and Saudi Arabia`},
  {enPage: 25, enTitle: `Graph: The world in 1965`},
  {enPage: 26, enTitle: `Graph: The world in 2017`},
  {enPage: 28, enTitle: `Danish TV interview`},
  {enPage: 29, enTitle: `Primary school completion rate`},
  {enPage: 30, enTitle: `Polls: Imagining the worst`},
  {enPage: 31, enTitle: `How many live in low-income countries?`},
  {enPage: 32, enTitle: `Where 75% of humanity lives`},
  {enPage: 32, enTitle: `Graph: Four income levels`},
  {enPage: 33, enTitle: `Doubling scales`},
  {enPage: 34, enTitle: `People on Level 1`},
  {enPage: 34, enTitle: `Average family size on Level 1`},
  {enPage: 34, enTitle: `Children working in the household`},
  {enPage: 34, enTitle: `Air pollution`},
  {enPage: 35, enTitle: `Cost of illness on Level 2`},
  {enPage: 35, enTitle: `Work in a garment factory`},
  {enPage: 36, enTitle: `Fridges and food on Level 2`},
  {enPage: 36, enTitle: `Traffic accidents on Level 3`},
  {enPage: 37, enTitle: `Education on Level 4`},
  {enPage: 37, enTitle: `Travel and vacation on Level 4`},
  {enPage: 37, enTitle: `Books on Level 4`},
  {enPage: 38, enTitle: `Historic poverty rate`},
  {enPage: 38, enTitle: `Incomes in Western Europe and the US in the 1950s`},
  {enPage: 38, enTitle: `Outdated terminology and the World Bank`},
  {enPage: 38, enTitle: `"Developing countries" in other organizations`},
  {enPage: 44, enTitle: `Poverty and extreme poverty`},
  {enPage: 45, enTitle: `Levels of poverty`},
  {enPage: 40, enTitle: `Overlapping spreads`},
  {enPage: [40, 41], enTitle: `Math scores`},
  {enPage: 41, enTitle: `Graphs: Incomes in Mexico & US`},
  {enPage: 42, enTitle: `In apartheid South Africa`},
  {enPage: 43, enTitle: `Brazilian income inequality`},
  {enPage: 48, enTitle: `Living conditions in 1950s Sweden`},
  {enPage: 49, enTitle: `Terrorism on the rise`},
  {enPage: 49, enTitle: `The State of World Fisheries`},
  {enPage: 49, enTitle: `Sea levels`},
  {enPage: 50, enTitle: `Graph: Better, worse, or about the same?`},
  {enPage: 50, enTitle: `When to trust the data`},
  {enPage: 52, enTitle: `Graph: Extreme poverty rate`},
  {enPage: 52, enTitle: `19th century living conditions`},
  {
    enPage: 53,
    enTitle: `Dip in extreme poverty: China, India and Latin America`
  },
  {enPage: 53, enTitle: `Life expectancy and data doubt`},
  {enPage: 53, enTitle: `Fact Question 4: Life Expectancy`},
  {enPage: 54, enTitle: `Historic child mortality`},
  {enPage: [54, 55], enTitle: `Deaths from starvation in Ethiopia`},
  {enPage: 55, enTitle: `Graph: Average life expectancy from 1800 to today`},
  {enPage: 56, enTitle: `World Food Programme.`},
  {enPage: 56, enTitle: `Swedes living on Level 4`},
  {enPage: 58, enTitle: `Not uncommon for children to drown`},
  {enPage: 58, enTitle: `Citizens of Lesotho`},
  {enPage: 58, enTitle: `Life expectancy in Lesotho and uncertainty of data`},
  {enPage: 58, enTitle: `Literacy in Sweden and India`},
  {enPage: 59, enTitle: `Vaccination on Level 1`},
  {enPage: 60, enTitle: `Graph: Legal slavery`},
  {enPage: 60, enTitle: `Graph: Oil spills`},
  {enPage: 60, enTitle: `Graph: Child mortality`},
  {enPage: 60, enTitle: `Graph: Death penalty`},
  {enPage: 60, enTitle: `Graph: Leaded gasoline`},
  {enPage: 61, enTitle: `Graph: Child labor`},
  {enPage: 61, enTitle: `Graph: Deaths from disaster`},
  {enPage: 61, enTitle: `Graph: Nuclear arms`},
  {enPage: 61, enTitle: `Graph: Smallpox`},
  {enPage: 61, enTitle: `Graph: Ozone depletion`},
  {enPage: 62, enTitle: `Graph: New movies`},
  {enPage: 62, enTitle: `Graph: Protected nature`},
  {enPage: 62, enTitle: `Graph: Women's right to vote`},
  {enPage: 62, enTitle: `Graph: New music`},
  {enPage: 62, enTitle: `Graph: Science`},
  {enPage: 62, enTitle: `Graph: Harvest`},
  {enPage: 62, enTitle: `Graph: Democracy`},
  {enPage: 62, enTitle: `Graph: Literacy`},
  {enPage: 63, enTitle: `Graph: Child cancer survival`},
  {enPage: 63, enTitle: `Graph: Girls in school`},
  {enPage: 63, enTitle: `Graph: Monitored species`},
  {enPage: 63, enTitle: `Graph: Electricity coverage`},
  {enPage: 63, enTitle: `Graph: Mobile phones`},
  {enPage: 63, enTitle: `Graph: Internet`},
  {enPage: 63, enTitle: `Graph: Immunization`},
  {enPage: 64, enTitle: `Graph: Guitars per capita`},
  {enPage: 66, enTitle: `Causes of death in human history`},
  {enPage: 66, enTitle: `Ancient graveyards and burial sites`},
  {enPage: 66, enTitle: `Historic child murders`},
  {enPage: 70, enTitle: `Educating girls`},
  {enPage: 73, enTitle: `Drownings`},
  {enPage: 75, enTitle: `Graph: Catching up with Sweden`},
  {enPage: 75, enTitle: `Ebola`},
  {enPage: 76, enTitle: `Lord Krishna's chessboard`},
  {enPage: 77, enTitle: `The world population is not just increasing`},
  {enPage: 78, enTitle: `Graph: Future number of children`},
  {enPage: 79, enTitle: `Teacher's conference in Norway`},
  {enPage: 79, enTitle: `Experts at the World Economic Forum`},
  {enPage: 79, enTitle: `The accuracy of UN Population forecasts`},
  {enPage: 80, enTitle: `Historic world population and three big cities`},
  {enPage: 80, enTitle: `Graph: World population from 8000 BC to today`},
  {enPage: 84, enTitle: `Graph: Babies per woman from 1800 to today`},
  {enPage: 85, enTitle: `Fertility transitions`},
  {enPage: 86, enTitle: `The inevitable fill-up`},
  {enPage: [87, 88], enTitle: `The Old Balance`},
  {enPage: 87, enTitle: `The new balance`},
  {enPage: 90, enTitle: `Graph: Average family size by income`},
  {enPage: 92, enTitle: `Two public health miracles`},
  {enPage: 92, enTitle: `Child survival`},
  {
    enPage: [93, 97],
    enTitle: `Graphs: 14 Straight lines, S-bends, slides, and humps`
  },
  {enPage: 97, enTitle: `E.coli Bacteria`},
  {enPage: [98, 99], enTitle: `CO2 emissions from transportation`},
  {enPage: 99, enTitle: `What part of the line are you seeing?`},
  {enPage: 105, enTitle: `Fear in polls`},
  {enPage: 107, enTitle: `Disaster data`},
  {enPage: 110, enTitle: `ReliefWeb`},
  {enPage: 111, enTitle: `Child deaths from diarrhea`},
  {enPage: 112, enTitle: `Plane accidents`},
  {enPage: 113, enTitle: `Deaths in wars`},
  {enPage: 114, enTitle: `Graph: Battle deaths`},
  {enPage: 114, enTitle: `Fukushima`},
  {enPage: 114, enTitle: `Chernobyl`},
  {enPage: 115, enTitle: `DDT`},
  {enPage: 116, enTitle: `Chemophobia`},
  {enPage: 116, enTitle: `Refusing vaccination`},
  {enPage: 116, enTitle: `The environmental movement`},
  {enPage: 118, enTitle: `Terrorism`},
  {enPage: 121, enTitle: `Alcohol deaths`},
  {enPage: 122, enTitle: `Risks of dying`},
  {
    enPage: 122,
    enTitle: `"How Many Deaths Make a Natural Disaster Newsworthy?"`
  },
  {enPage: [124, 125], enTitle: `Nacala child mortality calculation`},
  {enPage: 127, enTitle: `Saving lives`},
  {enPage: 128, enTitle: `Wrong proportions: Perils of Perception`},
  {enPage: 129, enTitle: `Educated mothers and child survival`},
  {enPage: 130, enTitle: `4.2 million`},
  {enPage: 131, enTitle: `Bach Mai Hospital`},
  {enPage: 132, enTitle: `The Vietnam War`},
  {enPage: [132, 133], enTitle: `Bears and axes`},
  {enPage: 133, enTitle: `The Spanish flu`},
  {enPage: 133, enTitle: `Tuberculosis (TB) and the swine flu`},
  {enPage: 134, enTitle: `Energy sources`},
  {enPage: 136, enTitle: `The world's PIN Code`},
  {enPage: 138, enTitle: `Graphs: West and Rest`},
  {enPage: 138, enTitle: `Future consumers`},
  {enPage: 139, enTitle: `Child mortality rate`},
  {enPage: 139, enTitle: `CO2 per capita`},
  {enPage: 151, enTitle: `The cost of diabetes`},
  {enPage: 155, enTitle: `Comparing stoves`},
  {enPage: 159, enTitle: `Graph: Differences within Africa`},
  {enPage: 160, enTitle: `Contraceptives in Sweden`},
  {enPage: 160, enTitle: `Family planning: Needs met and unmet needs`},
  {enPage: 160, enTitle: `Everything is made from chemicals`},
  {enPage: 161, enTitle: `The Salhi family on Dollar Street`},
  {enPage: 163, enTitle: `The recovery position`},
  {enPage: 163, enTitle: `Hong Kong report on SIDS`},
  {enPage: 169, enTitle: `The sense of superiority`},
  {enPage: 170, enTitle: `World Health Chart over 200 years`},
  {
    enPage: 170,
    enTitle: `Life expectancy 1970--2016: North Africa and Western Europe`
  },
  {enPage: 170, enTitle: `Speed of improvement over the decades`},
  {
    enPage: 170,
    enTitle: `Child mortality rates for Sub-Saharan Africa and Sweden`
  },
  {enPage: 171, enTitle: `Progress in China, Bangladesh, and Vietnam`},
  {enPage: 171, enTitle: `Mozambique and India`},
  {enPage: 171, enTitle: `Estimates of extreme poverty`},
  {enPage: 172, enTitle: `IMF forecasts`},
  {enPage: 172, enTitle: `80 years ago in Sweden and US`},
  {enPage: 174, enTitle: `Fertility in Iran`},
  {enPage: [175, 176], enTitle: `Graphs: Three groups based on religion`},
  {enPage: 175, enTitle: `Classifying major religions`},
  {enPage: 175, enTitle: `High income means low fertility`},
  {enPage: 176, enTitle: `Swedish values and RFSU`},
  {enPage: 177, enTitle: `Asian values`},
  {enPage: 177, enTitle: `Asian University for Women in Bangladesh`},
  {enPage: 179, enTitle: `Nature reserves`},
  {enPage: 179, enTitle: `Sri Lanka's earliest protected forest`},
  {enPage: 180, enTitle: `Outdated chimpanzee questions`},
  {enPage: 180, enTitle: `Swedish school system`},
  {enPage: 181, enTitle: `Attitudes toward same-sex marriage`},
  {
    enPage: 187,
    enTitle: `Expert forecasts: The single perspective in other books`
  },
  {enPage: 188, enTitle: `Lindau Nobel laureate meeting`},
  {enPage: 188, enTitle: `Poll results from groups of professionals`},
  {enPage: 189, enTitle: `Plundered natural resources`},
  {enPage: 192, enTitle: `Eradicating one disease at a time`},
  {enPage: 193, enTitle: `Falling profits of Big Pharma`},
  {enPage: 193, enTitle: `Education needs electricity`},
  {enPage: 197, enTitle: `Chart: Cuba`},
  {enPage: [198, 199], enTitle: `Chart: US Health Spendings`},
  {enPage: 201, enTitle: `Democracy Is Not the Single Solution`},
  {enPage: 201, enTitle: `Democracy and progress`},
  {enPage: 204, enTitle: `Neglected diseases`},
  {enPage: 207, enTitle: `Systems thinking`},
  {enPage: 208, enTitle: `How UNICEF gets the lowest prices`},
  {enPage: 210, enTitle: `Gapminder's Ignorance Project`},
  {enPage: 211, enTitle: `Poll results`},
  {enPage: 212, enTitle: `Why refugees don't fly`},
  {enPage: 214, enTitle: `CO2 emissions by income`},
  {enPage: 216, enTitle: `Syphilis`},
  {enPage: 216, enTitle: `1 billion people and Mao`},
  {enPage: 216, enTitle: `Falling birth rates and powerful leaders`},
  {enPage: 217, enTitle: `Family planning: Contraceptive usage by Catholics`},
  {enPage: 218, enTitle: `Access to safe abortion`},
  {enPage: 218, enTitle: `Institutions`},
  {
    enPage: 219,
    enTitle: `The governmental employees who saved the world from Ebola`
  },
  {enPage: 219, enTitle: `Thank you, industrial Revolution`},
  {enPage: 227, enTitle: `The Urgency Instinct in other books`},
  {enPage: 225, enTitle: `Roadblocks`},
  {enPage: 223, enTitle: `Konzo`},
  {enPage: 227, enTitle: `Now or never`},
  {enPage: 232, enTitle: `The melting ice cap`},
  {enPage: 232, enTitle: `Fresh numbers for GDP and CO2`},
  {enPage: 233, enTitle: `Climate refugees`},
  {enPage: 233, enTitle: `Climate reductionism and catastrophizing`},
  {enPage: 234, enTitle: `Ebola`},
  {enPage: 237, enTitle: `The risk of global pandemic`},
  {enPage: 238, enTitle: `The risk of financial collapse`},
  {enPage: 239, enTitle: `The risk of World War III`},
  {
    enPage: 239,
    enTitle: `The risk of climate change and plundering of natural resources`
  },
  {enPage: 240, enTitle: `The risk of extreme poverty`},
  {enPage: 247, enTitle: `Teachers`},
  {enPage: 250, enTitle: `Business`},
  {enPage: 251, enTitle: `Diversified economies`},
  {enPage: 252, enTitle: `Speling miskates`},
  {enPage: 252, enTitle: `Constructive news`},
  {enPage: 253, enTitle: `Local ignorance and data`}
].map(process)
